name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          corepack: true
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run linters
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Build the lib
        run: pnpm build
